# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 04 Oct 2018 15:58:26 +0000
*               @ALL          1
*               @user         8
